services:
  keeper-migrations:
    container_name: "keeper-migrations"
    environment:
      CONNECTION_STRING: "Server=mssql;Database=keeper-db;User Id=sa;Password=Admin@123"
    image: ${DOCKER_REGISTRY-}keeper-migrations
    build:
      context: .
      dockerfile: infrastructure/migrations/Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
  
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Admin@123"
    ports:
      - 1433:1433
    volumes:
      - ./sql-data:/var/opt/mssql
  
#  keeper-api:
#    container_name: "keeper-api"
#    environment:
#      prop: val
#    image: ${DOCKER_REGISTRY-}keeper-api
#    build:
#      context: .
#      dockerfile: src/Keeper.API/Dockerfile
#    ports:
#      - 8001:80
#    depends_on:
#      - redis