services:
  keeper-migrations:
    container_name: "keeper-migrations"
    image: ${DOCKER_REGISTRY-}keeper-migrations
    build:
      context: .
      dockerfile: infrastructure/migrations/Dockerfile
    depends_on:
      sql-db:
        condition: service_healthy
  
  sql-db:
    container_name: sql-db
    hostname: sql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Admin@123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Admin@123 -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    volumes:
      - ./data:/var/opt/mssql/data
      - ./log:/var/opt/mssql/log
      - ./secrets:/var/opt/mssql/secrets